version: '3.8'

services:
  pvc-service:
    build:
      context: .
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    ports:
      - "50052:50052"
    networks:
      - suedataplatform
    env_file:
      - .env.docker
    restart: always 

  redis-pvc:
    image: "redis:7.4-alpine"
    ports:
      - "6381:6379"
    volumes:
      - redis-data:/data
    networks:
      - suedataplatform
    environment:
      - REDIS_PASSWORD=redis
    command: ["redis-server", "--requirepass", "redis"]
    
volumes:
  redis-data:

networks:
  suedataplatform:
    external: true

