version: '3.8'

services:
  notebook-service:
    build:
      context: .
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    ports:
      - "50053:50053"
    networks:
      - suedataplatform
    env_file:
      - .env.docker
    restart: always 

  redis-notebook:
    image: "redis:7.4-alpine"
    environment:
      - REDIS_PASSWORD=redis
    networks:
      - suedataplatform
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--requirepass", "redis"] 

  mongo:
    image: mongo:8.0.1-noble
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "27017:27017"
    networks:
      - suedataplatform
    volumes:
      - mongo_data:/data/db  
  
networks:
  suedataplatform:
    external: true 

volumes:
  redis-data: 
  mongo_data:       